TAS-26/sign up
socious-io/shin-webapp pull request #8
Opened 2024-08-19 03:38 UTC by marjan-ara

2024-08-28 20:47 UTC, satanmourner requested changes

2024-08-28 20:47 UTC, satanmourner commented on src/modules/General/components/FileUploader/index.module.scss
> +    gap: 4px;
rem please

2024-08-28 20:47 UTC, satanmourner commented on src/modules/General/components/FileUploader/index.tsx
> +  const { t } = useTranslation();
`t` is not a clear word can you replace it with translate?

2024-08-28 20:47 UTC, satanmourner commented on src/modules/General/components/FileUploader/useFileUploader.tsx
> +  const { t } = useTranslation();
it is good to rename everywhere (replace it with `translate`)

2024-08-28 20:47 UTC, satanmourner commented on src/modules/General/components/FileUploader/useFileUploader.tsx
> +  // const { getRootProps, getInputProps } = useDropzone({ onDrop });
remove this comment if you don't use it

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/FormHeader/index.tsx
> +import React from 'react';
FormHeader move it into `SignUp/components/FormHeader`

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/StepperLayout/index.tsx
> +import React from 'react';
StepperLayout move it to `SignUp/components/StepperLayout`

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/StepperLayout/index.module.scss
> +.vertical-stepper {
follow BEM. you can use `.stepper`

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/StepperLayout/index.module.scss
> +    width: 440px;
rem please

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/StepperLayout/index.module.scss
> +    gap: 80px;
rem please

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/StepperLayout/index.module.scss
> +    @media (max-width: 640px) {
we don't have `640px` in responsive sizes (talwind). you should use `$md` (768px)

2024-08-28 20:47 UTC, satanmourner commented on src/modules/SignUp/StepperLayout/index.tsx
> +        <img src={'/images/logo/logo.svg'} alt="SHIN_LOGO" width="79px" height="32px" />
Do not use direct image for logo, import it from `assets` please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/detail/index.module.scss
> +    @media (min-width: 640px) {
use `$md` please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/detail/index.module.scss
> +        max-width: 480px;
rem please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.module.scss
> +    padding: 32px;
rem please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.module.scss
> +    padding: 32px;
54, 50 line too

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.module.scss
> +    max-width: 800px;
rem please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.tsx
> +        <img src={'/images/logo/logo.svg'} alt="SHIN_LOGO" width="79px" height="32px" />
import from `/assets` please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.tsx
> +      <div className={`w-full lg:min-w-[600px] ${css['formSection']}`}>
follow BEM. use `form` instead

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.tsx
> +                  style={{ display: 'flex', gap: '12px' }}
use `customStyle` prop instead please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/email/index.tsx
> +                  <img src={'/images/logo/socious-logo.svg'} alt="" />
import from `/assets` please

2024-08-28 20:47 UTC, satanmourner commented on src/pages/signUp/profile/index.module.scss
> +    }
- `$md`
- rem please

2024-08-29 02:13 UTC, marjan-ara commented on src/core/adaptors/media.ts
> +export interface UploadMediaAdaptorRes {
@satanmourner let's discuss it after daily
I think in API we should define required types by server (both in request and response), in adaptor we can map our types to api types

2024-08-29 09:37 UTC, satanmourner commented on src/core/adaptors/media.ts
> +export interface UploadMediaAdaptorRes {
whenever you change the adaptors as our convention, could you ping me to merge this PR? Thanks

2024-08-30 08:57 UTC, satanmourner approved these changes

2024-09-01 14:15 UTC, merged